stages:
  data_ingestion:
    cmd: python3 src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python3 src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/interim

  feature_engineering:
    cmd: python3 src/feature_engineering.py
    deps:
    - data/interim
    - src/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/processed

  model_training:
    cmd: python3 src/model_training.py
    deps:
    - data/processed
    - src/model_training.py
    params:
    - model_training.n_estimators
    - model_training.random_state
    outs:
    - model/model.pkl

  model_evalution:
    cmd: python3 src/model_evalution.py
    deps:
    - model/model.pkl
    - src/model_evalution.py
    metrics:
    - report/metrics.json
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
